WITH SALES_DATA AS (
    SELECT 
        S.BOOK_ID,
        B.AUTHOR_ID,
        B.CATEGORY,
        SUM(S.SALES) * B.PRICE AS TOTAL_SALES
    FROM BOOK_SALES S
    JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE LIKE '2022-01%'
    GROUP BY B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY
)
SELECT 
    S.AUTHOR_ID,
    A.AUTHOR_NAME,
    S.CATEGORY,
    SUM(S.TOTAL_SALES) AS TOTAL_SALES
FROM SALES_DATA S
JOIN AUTHOR A ON A.AUTHOR_ID = S.AUTHOR_ID
GROUP BY S.AUTHOR_ID, S.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;