WITH FIRST_GEN AS (
    SELECT 
        ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT 
        E.ID AS CHILD_ID
    FROM ECOLI_DATA E
    JOIN FIRST_GEN F ON E.PARENT_ID = F.ID
)
SELECT
    E.ID AS ID
FROM ECOLI_DATA E
JOIN SECOND_GEN S ON E.PARENT_ID = S.CHILD_ID
ORDER BY E.ID ASC;