WITH AVAILABLE_CARS AS (
    SELECT DISTINCT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' 
        AND END_DATE >= '2022-11-01'
    )
)
SELECT 
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR(30 * A.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)) AS FEE
FROM AVAILABLE_CARS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON A.CAR_TYPE = P.CAR_TYPE 
    AND P.DURATION_TYPE = '30일 이상'
WHERE FLOOR(30 * A.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)) >= 500000 
    AND FLOOR(30 * A.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;