WITH RECURSIVE GENERATIONS AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATIONS G ON E.PARENT_ID = G.ID
)
SELECT 
    COUNT(ID) AS COUNT,
    GENERATION
FROM GENERATIONS
WHERE ID NOT IN (
    SELECT PARENT_ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
GROUP BY GENERATION;