WITH FOOD_AMOUNT AS (
    SELECT 
        PRODUCT_ID,
        SUM(AMOUNT) AS AMOUNT,
        DATE_FORMAT(PRODUCE_DATE, "%Y-%m") AS PRODUCE_DATE
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID
)
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    A.AMOUNT * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_AMOUNT A ON P.PRODUCT_ID = A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
