WITH COUNT_REVIEW AS (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), 
TOP_REVIEWERS AS (
    SELECT MEMBER_ID
    FROM COUNT_REVIEW
    WHERE COUNT = (SELECT MAX(COUNT) FROM COUNT_REVIEW)
)
SELECT 
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW R
JOIN TOP_REVIEWERS T ON R.MEMBER_ID = T.MEMBER_ID
JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;

