SELECT ITEM_TREE.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
JOIN ITEM_TREE ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
WHERE PARENT_ITEM_ID IN (
    SELECT ITEM_TREE.ITEM_ID
    FROM ITEM_TREE
    JOIN ITEM_INFO ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM_TREE.ITEM_ID DESC;