WITH RENTAL_COUNT AS (
    SELECT 
        MONTH(START_DATE) AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH(START_DATE), CAR_ID
)
SELECT 
    r.MONTH,
    r.CAR_ID,
    r.RECORDS
FROM RENTAL_COUNT r
WHERE r.CAR_ID IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5    -- 전체 기간 동안 총 5회 이상 대여된 차량
)
ORDER BY MONTH ASC, CAR_ID DESC;