WITH MaxSizes AS (
 SELECT 
   YEAR(DIFFERENTIATION_DATE) as YEAR,
   MAX(SIZE_OF_COLONY) as max_size
 FROM ECOLI_DATA
 GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT 
 YEAR(e.DIFFERENTIATION_DATE) as YEAR,
 m.max_size - e.SIZE_OF_COLONY as YEAR_DEV,
 e.ID
FROM ECOLI_DATA e
JOIN MaxSizes m ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV;