SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH IS NOT NULL
AND (N.FISH_NAME, I.LENGTH) IN (
    SELECT N2.FISH_NAME, MAX(I2.LENGTH)
    FROM FISH_INFO I2
    JOIN FISH_NAME_INFO N2 ON I2.FISH_TYPE = N2.FISH_TYPE
    GROUP BY N2.FISH_NAME
);
