WITH TOTAL_SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
    GROUP BY BOOK_ID
)
SELECT 
    B.CATEGORY,
    SUM(T.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B
JOIN TOTAL_SALES T ON B.BOOK_ID = T.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC